input_1 = int(input(print("Enter the 1st word:- ")))
input_2 = input(print("Enter the 2nd word:- "))
input_3 = input(print("Enter the 3rd word:- "))
input_4 = input(print("Enter the 4th word:- "))
input_5 = input(print("Enter the 5th word:- "))
input_1.reverse()
input_2.reverse()
input_3.reverse()
input_4.reverse()
input_5.reverse()
print(f"{input_1}, {input_2}, {input_3}, {input_4}, {input_5}")