import turtle
turtle.Screen().bgcolor("Aqua")
board = turtle.Turtle()
for i in range(3):
    board.forward(100)
    board.left(120)
    board.forward(100)
    board.left(120)
    board.forward(100)
    board.penup()
    board.right(150)
    board.forward(50)
    board.pendown()
    board.right(90)
    board.forward(100)
    board.right(120)
    board.forward(100)
    board.right(120)
    board.forward(100)
for i in range(3):
    board.forward(150)
    board.right(120)
    board.forward(100)
    board.right(120)
    board.forward(100)
    board.penup()
    board.left(150)
    board.forward(50)
    board.pendown()
    board.left(90)
    board.forward(100)
    board.left(120)
    board.forward(100)
    board.left(120)
    board.forward(100)
turtle.done()                                                                                       
